// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVy-cHenIBIFfID5CACxHGLKCcJ5IaYS0',
    appId: '1:498016822640:web:1264e5fc005ef03defdbb5',
    messagingSenderId: '498016822640',
    projectId: 'budget-a06e1',
    authDomain: 'budget-a06e1.firebaseapp.com',
    storageBucket: 'budget-a06e1.appspot.com',
    measurementId: 'G-WTCLX15BB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCokQMyU-0M1FF4MPLL9PtvcEW5RRnwg4o',
    appId: '1:498016822640:android:14c029176cfe53c1efdbb5',
    messagingSenderId: '498016822640',
    projectId: 'budget-a06e1',
    storageBucket: 'budget-a06e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS3NAmeJahw5PehyzxebknRceR2hxfSSs',
    appId: '1:498016822640:ios:a72f3e3b1d6fbe1aefdbb5',
    messagingSenderId: '498016822640',
    projectId: 'budget-a06e1',
    storageBucket: 'budget-a06e1.appspot.com',
    iosClientId: '498016822640-alhtcc0jnv7h59si6o4qi13id9vnkt77.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS3NAmeJahw5PehyzxebknRceR2hxfSSs',
    appId: '1:498016822640:ios:a72f3e3b1d6fbe1aefdbb5',
    messagingSenderId: '498016822640',
    projectId: 'budget-a06e1',
    storageBucket: 'budget-a06e1.appspot.com',
    iosClientId: '498016822640-alhtcc0jnv7h59si6o4qi13id9vnkt77.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetManagement',
  );
}
